import { Theme, tokens, webDarkTheme } from '@fluentui/react-components';
import { DangerColors, SuccessColors, WarningColors } from './colors';

type AppTheme = Theme & {
	colorThemeSuccess10: string;
	colorThemeSuccess20: string;
	colorThemeSuccess30: string;
	colorThemeSuccess40: string;
	colorThemeSuccess50: string;
	colorThemeSuccess60: string;
	colorThemeSuccess70: string;
	colorThemeSuccess80: string;
	colorThemeSuccess90: string;
	colorThemeSuccess100: string;
	colorThemeSuccess110: string;
	colorThemeSuccess120: string;
	colorThemeSuccess130: string;
	colorThemeSuccess140: string;
	colorThemeSuccess150: string;
	colorThemeSuccess160: string;
	// Warning
	colorThemeWarning10: string;
	colorThemeWarning20: string;
	colorThemeWarning30: string;
	colorThemeWarning40: string;
	colorThemeWarning50: string;
	colorThemeWarning60: string;
	colorThemeWarning70: string;
	colorThemeWarning80: string;
	colorThemeWarning90: string;
	colorThemeWarning100: string;
	colorThemeWarning110: string;
	colorThemeWarning120: string;
	colorThemeWarning130: string;
	colorThemeWarning140: string;
	colorThemeWarning150: string;
	colorThemeWarning160: string;
	// Danger
	colorThemeDanger10: string;
	colorThemeDanger20: string;
	colorThemeDanger30: string;
	colorThemeDanger40: string;
	colorThemeDanger50: string;
	colorThemeDanger60: string;
	colorThemeDanger70: string;
	colorThemeDanger80: string;
	colorThemeDanger90: string;
	colorThemeDanger100: string;
	colorThemeDanger110: string;
	colorThemeDanger120: string;
	colorThemeDanger130: string;
	colorThemeDanger140: string;
	colorThemeDanger150: string;
	colorThemeDanger160: string;
};

export const appTheme = {
	...webDarkTheme,
	// Success
	colorThemeSuccess10: SuccessColors[10],
	colorThemeSuccess20: SuccessColors[20],
	colorThemeSuccess30: SuccessColors[30],
	colorThemeSuccess40: SuccessColors[40],
	colorThemeSuccess50: SuccessColors[50],
	colorThemeSuccess60: SuccessColors[60],
	colorThemeSuccess70: SuccessColors[70],
	colorThemeSuccess80: SuccessColors[80],
	colorThemeSuccess90: SuccessColors[90],
	colorThemeSuccess100: SuccessColors[100],
	colorThemeSuccess110: SuccessColors[110],
	colorThemeSuccess120: SuccessColors[120],
	colorThemeSuccess130: SuccessColors[130],
	colorThemeSuccess140: SuccessColors[140],
	colorThemeSuccess150: SuccessColors[150],
	colorThemeSuccess160: SuccessColors[160],
	// Warning
	colorThemeWarning10: WarningColors[10],
	colorThemeWarning20: WarningColors[20],
	colorThemeWarning30: WarningColors[30],
	colorThemeWarning40: WarningColors[40],
	colorThemeWarning50: WarningColors[50],
	colorThemeWarning60: WarningColors[60],
	colorThemeWarning70: WarningColors[70],
	colorThemeWarning80: WarningColors[80],
	colorThemeWarning90: WarningColors[90],
	colorThemeWarning100: WarningColors[100],
	colorThemeWarning110: WarningColors[110],
	colorThemeWarning120: WarningColors[120],
	colorThemeWarning130: WarningColors[130],
	colorThemeWarning140: WarningColors[140],
	colorThemeWarning150: WarningColors[150],
	colorThemeWarning160: WarningColors[160],
	// Danger
	colorThemeDanger10: DangerColors[10],
	colorThemeDanger20: DangerColors[20],
	colorThemeDanger30: DangerColors[30],
	colorThemeDanger40: DangerColors[40],
	colorThemeDanger50: DangerColors[50],
	colorThemeDanger60: DangerColors[60],
	colorThemeDanger70: DangerColors[70],
	colorThemeDanger80: DangerColors[80],
	colorThemeDanger90: DangerColors[90],
	colorThemeDanger100: DangerColors[100],
	colorThemeDanger110: DangerColors[110],
	colorThemeDanger120: DangerColors[120],
	colorThemeDanger130: DangerColors[130],
	colorThemeDanger140: DangerColors[140],
	colorThemeDanger150: DangerColors[150],
	colorThemeDanger160: DangerColors[160]
};

export const appTokens: Record<keyof AppTheme, string> = {
	...tokens,
	colorThemeSuccess10: `var(--colorThemeSuccess10)`,
	colorThemeSuccess20: `var(--colorThemeSuccess20)`,
	colorThemeSuccess30: `var(--colorThemeSuccess30)`,
	colorThemeSuccess40: `var(--colorThemeSuccess40)`,
	colorThemeSuccess50: `var(--colorThemeSuccess50)`,
	colorThemeSuccess60: `var(--colorThemeSuccess60)`,
	colorThemeSuccess70: `var(--colorThemeSuccess70)`,
	colorThemeSuccess80: `var(--colorThemeSuccess80)`,
	colorThemeSuccess90: `var(--colorThemeSuccess90)`,
	colorThemeSuccess100: `var(--colorThemeSuccess100)`,
	colorThemeSuccess110: `var(--colorThemeSuccess110)`,
	colorThemeSuccess120: `var(--colorThemeSuccess120)`,
	colorThemeSuccess130: `var(--colorThemeSuccess130)`,
	colorThemeSuccess140: `var(--colorThemeSuccess140)`,
	colorThemeSuccess150: `var(--colorThemeSuccess150)`,
	colorThemeSuccess160: `var(--colorThemeSuccess160)`,
	// Warning
	colorThemeWarning10: `var(--colorThemeWarning10)`,
	colorThemeWarning20: `var(--colorThemeWarning20)`,
	colorThemeWarning30: `var(--colorThemeWarning30)`,
	colorThemeWarning40: `var(--colorThemeWarning40)`,
	colorThemeWarning50: `var(--colorThemeWarning50)`,
	colorThemeWarning60: `var(--colorThemeWarning60)`,
	colorThemeWarning70: `var(--colorThemeWarning70)`,
	colorThemeWarning80: `var(--colorThemeWarning80)`,
	colorThemeWarning90: `var(--colorThemeWarning90)`,
	colorThemeWarning100: `var(--colorThemeWarning100)`,
	colorThemeWarning110: `var(--colorThemeWarning110)`,
	colorThemeWarning120: `var(--colorThemeWarning120)`,
	colorThemeWarning130: `var(--colorThemeWarning130)`,
	colorThemeWarning140: `var(--colorThemeWarning140)`,
	colorThemeWarning150: `var(--colorThemeWarning150)`,
	colorThemeWarning160: `var(--colorThemeWarning160)`,
	// Danger
	colorThemeDanger10: `var(--colorThemeDanger10)`,
	colorThemeDanger20: `var(--colorThemeDanger20)`,
	colorThemeDanger30: `var(--colorThemeDanger30)`,
	colorThemeDanger40: `var(--colorThemeDanger40)`,
	colorThemeDanger50: `var(--colorThemeDanger50)`,
	colorThemeDanger60: `var(--colorThemeDanger60)`,
	colorThemeDanger70: `var(--colorThemeDanger70)`,
	colorThemeDanger80: `var(--colorThemeDanger80)`,
	colorThemeDanger90: `var(--colorThemeDanger90)`,
	colorThemeDanger100: `var(--colorThemeDanger100)`,
	colorThemeDanger110: `var(--colorThemeDanger110)`,
	colorThemeDanger120: `var(--colorThemeDanger120)`,
	colorThemeDanger130: `var(--colorThemeDanger130)`,
	colorThemeDanger140: `var(--colorThemeDanger140)`,
	colorThemeDanger150: `var(--colorThemeDanger150)`,
	colorThemeDanger160: `var(--colorThemeDanger160)`
};
